name: CI Pipeline

on:
  push:
    branches:
      -main

jobs:
  test:
    runs-On: ubuntu-latest
    steps:
      -name: checkout code
      uses: actions/checkout@v3

      -name: setup node jobs
      uses: actions/setup-node@v3

      -name: Install Dependencies
      run: npm Install
      working-directory: january/jvl\ code\ devops\ basics

      -name: Run tests
      run: npm test 
      working-directory: january/jvl\ code\ devops\ basics

